### ISSUE TITLE
Addon not working (inputstreamhelper not found)

### ISSUE THREAD

**Issue by acidicX** [MrKrabat/plugin.video.crunchyroll#4]
Hey @MrKrabat,

as the older crunchyroll addon is only working partially for me (lots of errors), I decided to check yours out. For me it will not start though. I've tried it both on linux x64 (Arch) and Windows 8.1 64bit. Kodi v17.6.

Log:

```
19:43:14.833 T:140067655129152   DEBUG: ------ Window Deinit (Pointer.xml) ------
19:43:14.835 T:140067655129152   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.crunchyroll/)
19:43:14.836 T:140067655129152   DEBUG:   ParentPath = [plugin://plugin.video.crunchyroll/]
19:43:14.881 T:140065472673536   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.crunchyroll] took 46 ms
19:43:14.881 T:140065527297792   DEBUG: StartScript - calling plugin Crunchyroll('plugin://plugin.video.crunchyroll/','1','')
19:43:14.881 T:140065792481024   DEBUG: Thread LanguageInvoker start, auto delete: false
19:43:14.881 T:140065792481024    INFO: initializing python engine.
19:43:14.881 T:140065792481024   DEBUG: CPythonInvoker(10, /home/acidicx/.kodi/addons/plugin.video.crunchyroll/default.py): start processing
19:43:14.891 T:140065792481024   DEBUG: -->Python Interpreter Initialized<--
19:43:14.891 T:140065792481024   DEBUG: CPythonInvoker(10, /home/acidicx/.kodi/addons/plugin.video.crunchyroll/default.py): the source file to load is "/home/acidicx/.kodi/addons/plugin.video.crunchyroll/default.py"
19:43:14.891 T:140065792481024   DEBUG: CPythonInvoker(10, /home/acidicx/.kodi/addons/plugin.video.crunchyroll/default.py): setting the Python path to /home/acidicx/.kodi/addons/plugin.video.crunchyroll:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
19:43:14.891 T:140065792481024   DEBUG: CPythonInvoker(10, /home/acidicx/.kodi/addons/plugin.video.crunchyroll/default.py): entering source directory /home/acidicx/.kodi/addons/plugin.video.crunchyroll
19:43:14.899 T:140065792481024   DEBUG: CPythonInvoker(10, /home/acidicx/.kodi/addons/plugin.video.crunchyroll/default.py): instantiating addon using automatically obtained id of "plugin.video.crunchyroll" dependent on version 2.25.0 of the xbmc.python api
19:43:14.899 T:140065792481024   DEBUG: [PLUGIN] Crunchyroll: version 3.0.0 initialized
19:43:14.901 T:140065792481024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named inputstreamhelper
                                            Traceback (most recent call last):
                                              File "/home/acidicx/.kodi/addons/plugin.video.crunchyroll/default.py", line 33, in <module>
                                                from resources.lib import crunchyroll
                                              File "/home/acidicx/.kodi/addons/plugin.video.crunchyroll/resources/lib/crunchyroll.py", line 20, in <module>
                                                import inputstreamhelper
                                            ImportError: No module named inputstreamhelper
                                            -->End of Python script error report<--
19:43:14.925 T:140065792481024    INFO: Python script stopped
19:43:14.925 T:140065792481024   DEBUG: Thread LanguageInvoker 140065792481024 terminating
19:43:14.941 T:140067655129152   ERROR: GetDirectory - Error getting plugin://plugin.video.crunchyroll/
19:43:14.942 T:140067655129152   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll/) failed
19:43:14.942 T:140067655129152   DEBUG: CGUIMediaWindow::GetDirectory ()
19:43:14.942 T:140067655129152   DEBUG:   ParentPath = [plugin://plugin.video.crunchyroll/]
19:43:14.947 T:140065792481024   DEBUG: Thread BackgroundLoader start, auto delete: false
19:43:14.949 T:140067655129152   DEBUG: ------ Window Init (DialogNotification.xml) ------
19:43:14.954 T:140065792481024   DEBUG: Thread BackgroundLoader 140065792481024 terminating
19:43:15.716 T:140067655129152   DEBUG: Keyboard: scancode: 0x40, sym: 0x0134, unicode: 0x0000, modifier: 0x100
19:43:15.716 T:140067655129152   DEBUG: OnKey: alt-long-leftalt (0x104f0d4) pressed, action is
19:43:20.686 T:140067655129152   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
```

**Comment by MrKrabat** [comment]
Hi,
it looks like the dependency is not installed, normally Kodi should do that.
Can you check if inputstreamhelper is installed and activated?

**Comment by acidicX** [comment]
Ah, that was probably the issue. I just copied it into the .kodi/addons folder, but with the zip install method it installed the dependency. It's working now. Sorry, haven't done that a lot yet :)

The addon still says "inputstream.adaptive" is missing though, but the videos are starting!

**Comment by MrKrabat** [comment]
inputstreamhelper's job is to activate inputstream.adaptive and install the Widevine Library.
It should ask you in a dialog for permissions to do that.

In my experience not all videos will start, some will only start with inputstream.adaptive and some will work without :)
Its depending if your watching new anime or older ones.
