### ISSUE TITLE
Cant launch plugin

### ISSUE THREAD

**Issue by mxkle** [MrKrabat/plugin.video.crunchyroll#55]
Hi, 

i get an error when opening the plugin

my system:
```
arch linux 5.18.10-arch1-1
kodi build 19.4.0 
```

i got this from the kodi log:
```
2022-07-10 11:49:25.807 T:630     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'WindowsError' is not defined
                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.crunchyroll/resources/lib/api.py", line 136, in destroy
                                                       remove(getCookiePath(args))
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/kodi/.kodi/userdata/addon_data/plugin.video.crunchyroll/cookies.lwp'

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.crunchyroll/default.py", line 33, in <module>
                                                       crunchyroll.main(sys.argv)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.crunchyroll/resources/lib/crunchyroll.py", line 90, in main
                                                       if api.start(args):
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.crunchyroll/resources/lib/api.py", line 91, in start
                                                       req = request(args, "login", payload, True)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.crunchyroll/resources/lib/api.py", line 174, in request
                                                       destroy(args)
                                                     File "/var/lib/kodi/.kodi/addons/plugin.video.crunchyroll/resources/lib/api.py", line 137, in destroy
                                                       except WindowsError:
                                                   NameError: name 'WindowsError' is not defined
                                                   -->End of Python script error report<--

2022-07-10 11:49:25.815 T:630      INFO <general>: Python interpreter stopped
2022-07-10 11:49:25.818 T:629     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.crunchyroll/
2022-07-10 11:49:25.821 T:389     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll/) failed
```

full log is here: https://pastebin.com/wjgGQWy4

any help appreciated <3

**Comment by mxkle** [comment]
nvm found it out, wrong credentials :)
