### ISSUE TITLE
Devided by zero

### ISSUE THREAD

**Issue by tamodolo** [MrKrabat/plugin.video.crunchyroll#8]
The pluggin was just working when this error started to happen when I try to enter my queue:

14:46:26.512 T:139885398714112   ERROR: GetDirectory - Error getting
14:46:31.180 T:139884870235904   ERROR: Previous line repeats 6 times.
14:46:31.180 T:139884870235904   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ZeroDivisionError'>
                                            Error Contents: float division by zero
                                            Traceback (most recent call last):
                                              File "/home/id/.kodi/addons/plugin.video.crunchyroll/default.py", line 35, in <module>
                                                crunchyroll.main(sys.argv)
                                              File "/home/id/.kodi/addons/plugin.video.crunchyroll/resources/lib/crunchyroll.py", line 110, in main
                                                check_mode(args)
                                              File "/home/id/.kodi/addons/plugin.video.crunchyroll/resources/lib/crunchyroll.py", line 141, in check_mode
                                                controller.showQueue(args)
                                              File "/home/id/.kodi/addons/plugin.video.crunchyroll/resources/lib/controller.py", line 58, in showQueue
                                                "playcount":     1 if (100/float(item["most_likely_media"]["duration"]))*int(item["playhead"]) > 90 else 0,
                                            ZeroDivisionError: float division by zero
                                            -->End of Python script error report<--
14:46:31.198 T:139886640997888   ERROR: GetDirectory - Error getting plugin://plugin.video.crunchyroll/?mode=queue&title=Queue
14:46:31.198 T:139886640997888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll/?mode=queue&title=Queue) failed

Any ideas?

**Comment by tamodolo** [comment]
Now it's working again... I don't understand what's happening...

**Comment by tamodolo** [comment]
And then the same error started to happening again. It seems to be a random problem based on some argument that crunchyroll is passing or failing to pass. The item count of my queue have 139 entries.

**Comment by MrKrabat** [comment]
It seems that the Crunchyroll API returns zero as episode length for one of your queue entries (maybe a new aired episode that has 0 seconds length als placeholder).

I uploaded a fix into the master branch :)

**Comment by tamodolo** [comment]
Thank you very much! I'll test it and I'll be back to report
